name: Prod CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: deploy code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: {% raw %}${{ secrets.SSH_HOST }}{% endraw %}
          port: 22
          key: {% raw %}${{ secrets.SSH_KEY }}{% endraw %}
          username: {% raw %}${{ secrets.SSH_USERNAME }}{% endraw %}

          script: |
            git clone git@github.com:ryancheley/{{cookiecutter.project_slug}}.git

            source /home/{{cookiecutter.project_slug}}/venv/bin/activate
            
            rsync -av --delete --exclude=.env {{cookiecutter.project_slug}}/* {{cookiecutter.project_slug}}

            pip -q install -r /home/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/requirements.txt

            python /home/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/manage.py migrate

            python /home/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/manage.py collectstatic --noinput -v0

            systemctl daemon-reload
            systemctl restart {{cookiecutter.project_slug}}

            rm -rf {{cookiecutter.project_slug}}
